version: '3.8'

services:
  excalidraw-frontend:
    build: .
    environment:
      - REACT_APP_BACKEND_V2_GET_URL=http://excalidraw-backend:8080/api/v2/
      - REACT_APP_BACKEND_V2_POST_URL=http://excalidraw-backend:8080/api/v2/
    depends_on:
      excalidraw-backend:
        condition: service_healthy

  excalidraw-backend:
    image: excalidraw/excalidraw-room:latest
    environment:
      - PORT=8080
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes: {}